DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id INTEGER NOT NULL REFERENCES restaurant(id) ON DELETE CASCADE,
  placed_at TIMESTAMP NOT NULL,
  picked_up_at TIMESTAMP NOT NULL,
  status BOOLEAN DEFAULT TRUE
);
