DROP TABLE IF EXISTS orders CASCADE;
CREATE TABLE orders (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  restaurant_id INTEGER NOT NULL REFERENCES restaurant(id) ON DELETE CASCADE DEFAULT 1,
  placed_at TIMESTAMP,
  picked_up_at TIMESTAMP,
  status BOOLEAN DEFAULT TRUE
);
