DROP TABLE IF EXISTS carts CASCADE;
CREATE TABLE carts (
  id SERIAL PRIMARY KEY NOT NULL,
  menu_id INTEGER  NOT NULL REFERENCES menu_items(id) ON DELETE CASCADE,
  orders_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  quantity SMALLINT NOT NULL DEFAULT 1
);


